
public class Parameters {
	ReadFile rf;
	public double pi;
	public double mu0;
	public double muB;
	public double R;
	public double Na;
	public double g;
	public double kb;
	public double ta0;
	public double gamma_e;
	public double gl_scale;
	public double nano_size;
	public double elta_r_init;
	public double is_periodic;
	public double a0;
	public double dt_neel;
	public double d_neel;
	public double d_min;
	public double delta;
	public double eta_oleic;
	public double a3_eta_oleic;
	public double a2_eta_oleic;
	public double a1_eta_oleic;
	public double a0_eta_oleic;
	public int    ro_oleic;
	public double mol_mass_oleic;
	public int    rop;
	public double A_H ;
	public double N_oa;
	public double k_o;
	public double K1;
	public double Ms;
	public int    ro0;
	public double eta_car0;
	public double eta_car;
	public double mol_mass_car;
	public double alpha_damp;
	public int    T; 	 	           
	public double v_oleic;
	public double v_car;
	public double gradPerc;
	public int    BmanX;
	public int    BmanY;
	public int    BmanZ;
	public int    isAutoSetPosition;
	public double distances;
	public int    isShowInfo;
	public double dt0;
	public int    slow_steps;
	public double smooth_r;
	public int    is_large_mode;
	public double large_fraction;
	public double k_large;
	public int    load_at_start;
	public int    auto_save;
	public int    manual_field_control;
	public int    ext_field_is_homo;
	public int    auto_reversal;
	public int    setting_plot;
	public int    start_ideal;
	public int    ScreenCaptureStep;
	public int    AnalysisStep;
	public double d1;
	public double F1;
	public double d2;
	public double F2;
	public double d3;
	public double F3;
	public double d4;
	public double F4;
	public double d5;
	public double F5;
	public double d6;
	public double F6;
	public double d7;
	public double F7;
	public double d8;
	public double F8;
	public double d9;
	public double F9;
	public double d10;
	public double F10;
	public double d11;
	public double F11;
	public double d12;
	public double F12;
	public double d13;
	public double F13;
	public double d14;
	public double F14;
	public int    PositionMax;
	public double x1;
	public double y1;
	public double z1;
	public int    pts1;
	public double x2;
	public double y2;
	public double z2;
	public int    pts2;
	public double x3;
	public double y3;
	public double z3;
	public int    pts3;
	public double x4;
	public double y4;
	public double z4;
	public int    pts4;
	public double x5;
	public double y5;
	public double z5;
	public int    pts5;
	public double x6;
	public double y6;
	public double z6;
	public int    pts6;
	public int    n;
	public int    T0;
	public int    T1;
	public int    T2;
	public int    T3;
	public int    T4;
	public int    T5;
	public int    T6;
	public int    T7;
	public int    T8;
	public int    T9;
	public int    T10;
	public int    T11;
	public int    T12;
	public int    T13;
	public int    T14;
	public int    T15;
	public int    T16;
	public int    T17;
	public int    T18;
	public int    T19;
	public int    T20;
	public int    T21;
	public int    T22;
	public int    T23;
	public int    T24;
	public int    T25;
	public int    T26;
	public int    T27;
	public double    eta0;
	public double    eta1;
	public double    eta2;
	public double    eta3;
	public double    eta4;
	public double    eta5;
	public double    eta6;
	public double    eta7;
	public double    eta8;
	public double    eta9;
	public double    eta10;
	public double    eta11;
	public double    eta12;
	public double    eta13;
	public double    eta14;
	public double    eta15;
	public double    eta16;
	public double    eta17;
	public double    eta18;
	public double    eta19;
	public double    eta20;
	public double    eta21;
	public double    eta22;
	public double    eta23;
	public double    eta24;
	public double    eta25;
	public double    eta26;
	public double    eta27;
	public int    FileType;
	
	public Parameters (String path) {
		rf=new ReadFile(path);
	
	                            //Mathematical Constants
	pi                   = rf.get("MathConst", "pi", 1.0);
								//Physics Constants
	mu0                  = rf.get("PhysConst", "mu0",     1.0); 
	muB			 	     = rf.get("PhysConst", "muB", 	1.0);
	R 		     	     = rf.get("PhysConst", "R", 		1.0);
	Na 		     	     = rf.get("PhysConst", "Na",      1.0);
	g 		     	     = rf.get("PhysConst", "g",       1.0);
	kb 		     	     = rf.get("PhysConst", "kb",      1.0);
	ta0 		         = rf.get("PhysConst", "ta0",     1.0);
	gamma_e        	     = rf.get("PhysConst", "gamma_e", 1.0);
	 							//Space Parameters
	gl_scale       	     = rf.get("Space", "gl_scale",     1.0);
	nano_size      	     = rf.get("Space", "nano_size",    1.0);
	elta_r_init    	     = rf.get("Space", "delta_r_init", 1.0);
	is_periodic     	 = rf.get("Space", "is_periodic",  1.0);
	 						 	//Experimental Parameters of Materials
	a0 	 	     	     = rf.get("ExperimentalMaterial", "a0",             1.0);
	dt_neel 	 	     = rf.get("ExperimentalMaterial", "dt_neel",        1.0);
	d_neel 	 	 	     = rf.get("ExperimentalMaterial", "d_neel",         1.0);
	d_min 	 	 	     = rf.get("ExperimentalMaterial", "d_min",          1.0);
	delta 	 	 	     = rf.get("ExperimentalMaterial", "delta",          1.0);
	eta_oleic 	 	     = rf.get("ExperimentalMaterial", "eta_oleic",      1.0);
	a3_eta_oleic 	 	 = rf.get("ExperimentalMaterial", "a3_eta_oleic",   1.0);
	a2_eta_oleic 	 	 = rf.get("ExperimentalMaterial", "a2_eta_oleic",   1.0);
	a1_eta_oleic 		 = rf.get("ExperimentalMaterial", "a1_eta_oleic",   1.0);
	a0_eta_oleic 	     = rf.get("ExperimentalMaterial", "a0_eta_oleic",   1.0);
    ro_oleic 	 	     = rf.get("ExperimentalMaterial", "ro_oleic",       -5);
	mol_mass_oleic       = rf.get("ExperimentalMaterial", "mol_mass_oleic", 1.0);
	rop 	 	     	 = rf.get("ExperimentalMaterial", "rop",            -5);
	A_H 			 	 = rf.get("ExperimentalMaterial", "A_H",            1.0);
	N_oa 	 		 	 = rf.get("ExperimentalMaterial", "N_oa",           1.0);
	k_o 	 		 	 = rf.get("ExperimentalMaterial", "k_o",            1.0);
	K1 	 		 	     = rf.get("ExperimentalMaterial", "K1",             1.0);
	Ms 	 		 	     = rf.get("ExperimentalMaterial", "Ms",             1.0);
	ro0 	 	     	 = rf.get("ExperimentalMaterial", "ro0",            -5);
	eta_car0 			 = rf.get("ExperimentalMaterial", "eta_car0",       1.0);
	eta_car 	         = rf.get("ExperimentalMaterial", "eta_car",        1.0);
	mol_mass_car 	     = rf.get("ExperimentalMaterial", "mol_mass_car",   1.0);
	alpha_damp 	         = rf.get("ExperimentalMaterial", "alpha_damp",     1.0);
	 					      //Experimental Conditions 
	T 	 	             = rf.get("ExperimentalConditions", "T",        -5);
	v_oleic 		     = rf.get("ExperimentalConditions", "v_oleic",  1.0);
	v_car 	             = rf.get("ExperimentalConditions", "v_car",    1.0);
	gradPerc 	 	     = rf.get("ExperimentalConditions", "gradPerc", 1.0);
	BmanX 	 	         = rf.get("ExperimentalConditions", "BmanX",    -5);
	BmanY 	 	         = rf.get("ExperimentalConditions", "BmanY",    -5);
	BmanZ 	 	         = rf.get("ExperimentalConditions", "BmanZ",    -5);
	                          //Simulation Setup
	isAutoSetPosition    = rf.get("SimulationSetup", "isAutoSetPosition",     -5);
	distances 	         = rf.get("SimulationSetup", "distances", 			1.0);
	isShowInfo           = rf.get("SimulationSetup", "isShowInfo",		    -5);
	dt0        	         = rf.get("SimulationSetup", "dt0",                   1.0);
	slow_steps           = rf.get("SimulationSetup", "slow_steps",            -5);
	smooth_r  	         = rf.get("SimulationSetup", "smooth_r", 		        1.0);
	is_large_mode        = rf.get("SimulationSetup", "is_large_mode",         -5);
	large_fraction       = rf.get("SimulationSetup", "large_fraction",        1.0);
	k_large  	         = rf.get("SimulationSetup", "k_large",               1.0);
	load_at_start        = rf.get("SimulationSetup", "load_at_start",         -5);
	auto_save 		     = rf.get("SimulationSetup", "auto_save", 			-5);
	manual_field_control = rf.get("SimulationSetup", "manual_field_control",  -5);
	ext_field_is_homo    = rf.get("SimulationSetup", "ext_field_is_homo", 	-5);
	auto_reversal  	     = rf.get("SimulationSetup", "auto_reversal",	        -5);
	setting_plot         = rf.get("SimulationSetup", "setting_plot",		    -5);
	start_ideal  	     = rf.get("SimulationSetup", "start_ideal", 		    -5);
	ScreenCaptureStep    = rf.get("SimulationSetup", "ScreenCaptureStep",     -5);
	AnalysisStep   	     = rf.get("SimulationSetup", "AnalysisStep",          -5);
						        //Model Size Dispersion
	d1        	         = rf.get("ModelSizeDispersion", "d1",  1.0);
	F1 	                 = rf.get("ModelSizeDispersion", "F1",  1.0);
	d2        	         = rf.get("ModelSizeDispersion", "d2",  1.0);
	F2 	                 = rf.get("ModelSizeDispersion", "F2",  1.0);
	d3        	         = rf.get("ModelSizeDispersion", "d3",  1.0);
	F3 	                 = rf.get("ModelSizeDispersion", "F3",  1.0);
	d4        	         = rf.get("ModelSizeDispersion", "d4",  1.0);
	F4 	                 = rf.get("ModelSizeDispersion", "F4",  1.0);
	d5        	         = rf.get("ModelSizeDispersion", "d5",  1.0);
	F5 	                 = rf.get("ModelSizeDispersion", "F5",  1.0);
	d6        	         = rf.get("ModelSizeDispersion", "d6",  1.0);
	F6 	                 = rf.get("ModelSizeDispersion", "F6",  1.0);
	d7        	         = rf.get("ModelSizeDispersion", "d7",  1.0);
	F7 	                 = rf.get("ModelSizeDispersion", "F7",  1.0);
	d8        	         = rf.get("ModelSizeDispersion", "d8",  1.0);
	F8 	                 = rf.get("ModelSizeDispersion", "F8",  1.0);
	d9        	         = rf.get("ModelSizeDispersion", "d9",  1.0);
	F9 	                 = rf.get("ModelSizeDispersion", "F9",  1.0);
	d10        	         = rf.get("ModelSizeDispersion", "d10", 1.0);
	F10 	             = rf.get("ModelSizeDispersion", "F10", 1.0);
	d11        	         = rf.get("ModelSizeDispersion", "d11", 1.0);
	F11 	             = rf.get("ModelSizeDispersion", "F11", 1.0);
	d12        	         = rf.get("ModelSizeDispersion", "d12", 1.0);
	F12 	             = rf.get("ModelSizeDispersion", "F12", 1.0);
	d13        	         = rf.get("ModelSizeDispersion", "d13", 1.0);
	F13 	             = rf.get("ModelSizeDispersion", "F13", 1.0);
	d14        	         = rf.get("ModelSizeDispersion", "d14", 1.0);
	F14 	             = rf.get("ModelSizeDispersion", "F14", 1.0);
								 // Set Position
	PositionMax          = rf.get("SetPosition", "PositionMax", -5);
	x1 	                 = rf.get("SetPosition", "x1", 1.0);
	y1 	                 = rf.get("SetPosition", "y1", 1.0);
	z1 	                 = rf.get("SetPosition", "z1", 1.0);
	pts1                 = rf.get("SetPosition", "pts1", -5);
	x2 	                 = rf.get("SetPosition", "x2", 1.0);
	y2 	                 = rf.get("SetPosition", "y2", 1.0);
	z2 	                 = rf.get("SetPosition", "z2", 1.0);
	pts2                 = rf.get("SetPosition", "pts2", -5);
	x3 	                 = rf.get("SetPosition", "x3", 1.0);
	y3 	                 = rf.get("SetPosition", "y3", 1.0);
	z3 	                 = rf.get("SetPosition", "z3", 1.0);
	pts3                 = rf.get("SetPosition", "pts3", -5);
	x4 	                 = rf.get("SetPosition", "x4", 1.0);
	y4 	                 = rf.get("SetPosition", "y4", 1.0);
	z4 	                 = rf.get("SetPosition", "z4", 1.0);
	pts4                 = rf.get("SetPosition", "pts4", -5);
	x5 	                 = rf.get("SetPosition", "x5", 1.0);
	y5 	                 = rf.get("SetPosition", "y5", 1.0);
	z5 	                 = rf.get("SetPosition", "z5", 1.0);
	pts5                 = rf.get("SetPosition", "pts5", -5);
	x6 	                 = rf.get("SetPosition", "x6", 1.0);
	y6 	                 = rf.get("SetPosition", "y6", 1.0);
	z6 	                 = rf.get("SetPosition", "z6", 1.0);
	pts6                 = rf.get("SetPosition", "pts6", -5);
		                        //EtaCarPoints
	n                    = rf.get("EtaCarPoints", "n",   -5);
	T0                   = rf.get("EtaCarPoints", "T0",  -5);
	T1                   = rf.get("EtaCarPoints", "T1",  -5);
	T2                   = rf.get("EtaCarPoints", "T2",  -5);
	T3                   = rf.get("EtaCarPoints", "T3",  -5);
	T4                   = rf.get("EtaCarPoints", "T4",  -5);
	T5                   = rf.get("EtaCarPoints", "T5",  -5);
	T6                   = rf.get("EtaCarPoints", "T6",  -5);
	T7                   = rf.get("EtaCarPoints", "T7",  -5);
	T8                   = rf.get("EtaCarPoints", "T8",  -5);
	T9                   = rf.get("EtaCarPoints", "T9",  -5);
	T10                  = rf.get("EtaCarPoints", "T10", -5);
	T11                  = rf.get("EtaCarPoints", "T11", -5);
	T12                  = rf.get("EtaCarPoints", "T12", -5);
	T13                  = rf.get("EtaCarPoints", "T13", -5);
	T14                  = rf.get("EtaCarPoints", "T14", -5);
	T15                  = rf.get("EtaCarPoints", "T15", -5);
	T16                  = rf.get("EtaCarPoints", "T16", -5);
	T17                  = rf.get("EtaCarPoints", "T17", -5);
	T18                  = rf.get("EtaCarPoints", "T18", -5);
	T19                  = rf.get("EtaCarPoints", "T19", -5);
	T20                  = rf.get("EtaCarPoints", "T20", -5);
	T21                  = rf.get("EtaCarPoints", "T21", -5);
	T22                  = rf.get("EtaCarPoints", "T22", -5);
	T23                  = rf.get("EtaCarPoints", "T23", -5);
	T24                  = rf.get("EtaCarPoints", "T24", -5);
    T25                  = rf.get("EtaCarPoints", "T25", -5);
	T26                  = rf.get("EtaCarPoints", "T26", -5);
	T27                  = rf.get("EtaCarPoints", "T27", -5);
	
	eta0                 = rf.get("EtaCarPoints", "eta0",  1.0);
	eta1                 = rf.get("EtaCarPoints", "eta1",  1.0);
	eta2                 = rf.get("EtaCarPoints", "eta2",  1.0);
	eta3                 = rf.get("EtaCarPoints", "eta3",  1.0);
	eta4                 = rf.get("EtaCarPoints", "eta4",  1.0);
	eta5                 = rf.get("EtaCarPoints", "eta5",  1.0);
	eta6                 = rf.get("EtaCarPoints", "eta6",  1.0);
	eta7                 = rf.get("EtaCarPoints", "eta7",  1.0);
	eta8                 = rf.get("EtaCarPoints", "eta8",  1.0);
	eta9                 = rf.get("EtaCarPoints", "eta9",  1.0);
	eta10                = rf.get("EtaCarPoints", "eta10", 1.0);
	eta11                = rf.get("EtaCarPoints", "eta11", 1.0);
	eta12                = rf.get("EtaCarPoints", "eta12", 1.0);
	eta13                = rf.get("EtaCarPoints", "eta13", 1.0);
	eta14                = rf.get("EtaCarPoints", "eta14", 1.0);
	eta15                = rf.get("EtaCarPoints", "eta15", 1.0);
	eta16                = rf.get("EtaCarPoints", "eta16", 1.0);
	eta17                = rf.get("EtaCarPoints", "eta17", 1.0);
	eta18                = rf.get("EtaCarPoints", "eta18", 1.0);
	eta19                = rf.get("EtaCarPoints", "eta19", 1.0);
	eta20                = rf.get("EtaCarPoints", "eta20", 1.0);
	eta21                = rf.get("EtaCarPoints", "eta21", 1.0);
	eta22                = rf.get("EtaCarPoints", "eta22", 1.0);
	eta23                = rf.get("EtaCarPoints", "eta23", 1.0);
	eta24                = rf.get("EtaCarPoints", "eta24", 1.0);
	eta25                = rf.get("EtaCarPoints", "eta25", 1.0);
	eta26                = rf.get("EtaCarPoints", "eta26", 1.0);
	eta27                = rf.get("EtaCarPoints", "eta27", 1.0);
									//Image   Settings
	FileType             = rf.get("ImageSettings", "FileType", -5);
	}
	
}
